server:
  port: 8080
spring:
  application:
    name: producer-rabbitmq
  cloud:
    stream:
      bindings:
        input-in-0:
          group: ${RABBIT_GROUP:DemoGroup}
          consumer:
            batch-mode: true
        output-out-0:
          producer:
            error-channel-enabled: true
      source: output
      rabbit:
        bindings:
          output-out-0:
            producer:
              useConfirmHeader: true
          input-in-0:
            consumer:
              auto-bind-dlq: true
              batch-size: 10

  rabbitmq:
    publisher-confirm-type: correlated
    publisher-returns: true
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:user}
    password: ${RABBIT_PASSWORD:password}

